#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2022 Eugenio "g7" Paolantonio <me@medesimo.eu>
#
# Rewrote it for PKGBUILD (aarchd)
# Copyright (C) 2025 Deepak Meena <notwho53@gmail.com>

# Common packages for every api level
COMMON_PACKAGES = [
	"android-base",
	"lxc-android",
	"libhybris",
	"libhybris-utils",
	#"hadess-sensorfw-proxy",
	"droidian-quirks-hybris-gl",
	"droidian-quirks-tls-padding",
	"droidian-quirks-xtables-legacy",
	"gst-droid",
	#"flash-bootimage",
	"droidian-quirks-device",
	"flashlightd",
]

COMMON_PHOSH = [
	"phosh-config-hwcomposer",
]

# Common packages for phones
COMMON_PHONE_PACKAGES = [
	"adaptation-hybris-common",
	#"ofono",
	#"ofono-scripts",
	#"ofono2mm",
]

# Devtools packages
COMMON_DEVTOOLS_PACKAGES = [
	"adaptation-hybris-common",
	"libhybris-test",
	"hybris-usb",
	"openssh",
]

# Common packages for api levels 16+
COMMON_16_PACKAGES = [
	"adaptation-hybris-common",
	"pulseaudio-config-droid",
	"droidian-quirks-api%(level)d",
]

# Common packages for api levels 16 through 29 (4.1 to 29)
COMMON_16_29_PACKAGES = [
	"pulseaudio-modules-droid-jb2q",
]

# Common packages for api levels 30+ (11+)
COMMON_30_PACKAGES = [
	"pulseaudio-modules-droid-modern",
]

# Common packages for api levels 26+ (8+)
COMMON_26_PACKAGES = [
	"bluebinder",
	"timekeeper",
]

# Common phone packages for api levels 26+ (8+)
COMMON_26_PHONE_PACKAGES = [
	"adaptation-hybris-common",
	"adaptation-hybris-phone",
	"adaptation-hybris-api%(level)s",
	#"ofono-binder-plugin",
	#"ofono-configs-binder-common",
	"pulseaudio-modules-droid-hidl",
	"audiosystem-passthrough",
]

# DISABLED
# Common phone packages for dual sim devices for api levels 26+ (8+)
# COMMON_26_DUAL_SIM_PACKAGES = [
# 	"adaptation-hybris-api%(level)d-phone",
# 	"ofono-configs-binder-dual-sim",
# ]

SUPPORTED_APILEVELS = {
	0 : {
		"common" : COMMON_PACKAGES,
		"phone"    : COMMON_PHONE_PACKAGES,
		"devtools" : COMMON_DEVTOOLS_PACKAGES,
		"phosh"    : COMMON_PHOSH,
	},
	28 : {
		"standard"       : COMMON_16_PACKAGES + COMMON_16_29_PACKAGES + COMMON_26_PACKAGES,
		"phone"          : COMMON_26_PHONE_PACKAGES,
		#"phone-dual-sim" : COMMON_26_DUAL_SIM_PACKAGES,
	},
	29 : {
		"standard"       : COMMON_16_PACKAGES + COMMON_16_29_PACKAGES + COMMON_26_PACKAGES,
		"phone"          : COMMON_26_PHONE_PACKAGES,
		#"phone-dual-sim" : COMMON_26_DUAL_SIM_PACKAGES,
	},
	30 : {
		"standard"       : COMMON_16_PACKAGES + COMMON_30_PACKAGES + COMMON_26_PACKAGES,
		"phone"          : COMMON_26_PHONE_PACKAGES,
		#"phone-dual-sim" : COMMON_26_DUAL_SIM_PACKAGES,
	},
        32 : {
                "standard"       : COMMON_16_PACKAGES + COMMON_30_PACKAGES + COMMON_26_PACKAGES,
                "phone"          : COMMON_26_PHONE_PACKAGES,
                #"phone-dual-sim" : COMMON_26_DUAL_SIM_PACKAGES,
        },
        33 : {
                "standard"       : COMMON_16_PACKAGES + COMMON_30_PACKAGES + COMMON_26_PACKAGES,
                "phone"          : COMMON_26_PHONE_PACKAGES,
                #"phone-dual-sim" : COMMON_26_DUAL_SIM_PACKAGES,
        },
}

HEADER = """\
# This file is generated by genpkgbuild.py
# Maintainer: Deepak Meena <notwho53@gmail.com>
pkgbase=adaptation-hybris
pkgver=29
pkgrel=1
arch=(any)
license=('custom')
url="https://aarchd.who53.me"
source=()
md5sums=()
"""

SPLIT_TEMPLATE = """
package_%(pkgname)s() {
    pkgdesc="Base metapackage for %(basepkg)s adaptations (%(variant)s variant)"
    depends=(%(depends)s)
}
"""

def sanitize(name):
    return name.replace("_", "-")

if __name__ == "__main__":
    with open("PKGBUILD", "w") as f:
        f.write(HEADER)
        f.write("\npkgname=(")
        names = []

        for level, variants in SUPPORTED_APILEVELS.items():
            for variant, deps in variants.items():
                basepkg = f"adaptation-hybris-api{level}" if level > 0 else "adaptation-hybris"
                pkgname = f"{basepkg}-{variant}" if variant != "standard" else basepkg
                names.append(pkgname)

        for name in names:
            f.write(f'\n  "{name}"')
        f.write("\n)\n")

        for level, variants in SUPPORTED_APILEVELS.items():
            for variant, deps in variants.items():
                subs = {
                    "level": level,
                }

                formatted_deps = []
                for dep in deps:
                    try:
                        formatted_deps.append('"' + (dep % subs) + '"')
                    except:
                        formatted_deps.append(f'"{dep}"')

                basepkg = f"adaptation-hybris-api{level}" if level > 0 else "adaptation-hybris"
                pkgname = f"{basepkg}-{variant}" if variant != "standard" else basepkg

                f.write(SPLIT_TEMPLATE % {
                    "pkgname": pkgname,
                    "basepkg": basepkg,
                    "variant": variant,
		    "depends": "\n\t" + "\n\t".join(formatted_deps)
                })
