name: Build Packages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone build-tools repo
        run: |
          git clone https://github.com/aarchd/build-tools /tmp/build-tools

      - name: Run pkgmeta.sh gen
        run: /tmp/build-tools/pkgmeta.sh gen

      - name: Fetch build-metadata from meta branch
        run: |
          git fetch origin meta
          git show meta:build-metadata > build-metadata

      - name: Get changed packages
        run: |
          pkgs=$(/tmp/build-tools/pkgmeta.sh check)
          echo "CHANGED_PKGS=$pkgs" >> "$GITHUB_ENV"

      - name: Pull rootfs
        run: |
          gh release download -R "aarchD/rootfs" -p "rootfs.tar.gz"
          tar -xzf rootfs.tar.gz -C /tmp/rootfs

      - name: Build changed packages
        if: env.CHANGED_PKGS != ''
        run: |
          mkdir -p /tmp/pkgs
          sudo systemd-nspawn -D /tmp/rootfs --bind=$PWD:/mnt/PKGBUILDs --bind=/tmp/build-tools:/mnt/build-tools --bind=/tmp/pkgs:/mnt/pkgs /bin/bash -c " \
            /mnt/build-tools/buildpkg.sh $CHANGED_PKGS "

      - name: Update build-metadata
        if: env.CHANGED_PKGS != ''
        run: |
          /tmp/build-tools/pkgmeta.sh buildc
          mv build-metadata ../
          git switch meta
          mv ../build-metadata .
          git add build-metadata
          git commit --amend --no-edit
          git push origin meta --force

      - name: Push packages
        if: env.CHANGED_PKGS != ''
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://$PAT@github.com/aarch0/repo.git --depth=1
          cd repo && mkdir -p PKGS/

          for pkg in /tmp/pkgs/*.pkg.tar.zst; do
            base=$(basename "$pkg")
            prefix="${base%%-*}"
            find PKGS/ -type f -name "${prefix}-*.pkg.tar.zst" -exec rm -v {} +
          done

          cp /tmp/pkgs/* PKGS/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A -v
          git commit -m "${GITHUB_SHA::7} - $CHANGED_PKGS"
          git push origin main
